// vim:ft=aptconf
APT::Install-Recommends "0";
APT::Clean-Installed "0";
/* Debug::pkgDPkgProgressReporting "1"; */
DPkg::ConfigurePending "0";
DPkg::Tools::options::cmd::InfoFD "1";
DPkg::options {
"--root";
"/data/data/com.termux/files/home/apt/test";
/* "/"; */
/* "--admindir"; */
/* "/data/data/com.termux/files/home/apt/test/var/lib/dpkg"; */
/* "/data/data/com.termux/files/usr/glibc/var/lib/dpkg"; */
;
}
Dir::Etc::sourceparts "";
Dir::Cache "/data/data/com.termux/files/usr/glibc/var/cache/apt";
/* Dir::Cache "/data/data/com.termux/files/home/apt/test/var/cache/apt"; */

/* test root */

/* Dir::Bin::dpkg "/data/data/com.termux/files/home/termux-packages/packages/glibc-solo/dpkgx"; */
Dir::Etc::sourcelist "/data/data/com.termux/files/home/termux-packages/packages/glibc-solo/glibc.sources";
Dir::State "/data/data/com.termux/files/home/apt/test/var/lib/apt";
/* Dir::State::status "/data/data/com.termux/files/home/apt/test/var/lib/dpkg/status"; */
Dir::State::status "/data/data/com.termux/files/home/apt/test/data/data/com.termux/files/usr/var/lib/dpkg/status";

/* Dir::Cache::archives "/data/data/com.termux/files/home/apt/test/var/cache/apt/archives"; */ 

/* real root */

/* Dir::Bin::dpkg "/data/data/com.termux/files/usr/etc/apt/dpkgx"; */
/* Dir::Etc::sourcelist "/data/data/com.termux/files/usr/etc/apt/glibc.sources"; */
/* Dir::State "/data/data/com.termux/files/usr/glibc/var/lib/apt"; */
/* Dir::State::status "/data/data/com.termux/files/usr/glibc/var/lib/dpkg/status"; */

/* Dir::Cache::archives "/data/data/com.termux/files/usr/glibc/var/cache/apt/archives"; */ 
/* Dir::Etc::sourcelist "/data/data/com.termux/files/usr/glibc/etc/apt/sources.list.d/glibc.list"; */
